version: "3.9"

services:
  business-magician:
    build: ./magicians/business
    ports:
      - "8081:8080"

  job-magician:
    build: ./magicians/job
    ports:
      - "8082:8080"

  creative-magician:
    build: ./magicians/creative
    ports:
      - "8083:8080"

  developer-magician:
    build: ./magicians/developer
    ports:
      - "8084:8080"
